Greenter\Ubl\Entity\CommonAggregateComponents\ImmobilizedSecurity:
    xml_root_name: ImmobilizedSecurity
    xml_root_namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2'
